{
 "title": "SNOW Observability",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "server",
    "query": {}
   },
   {
    "name": "botType",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kamas to sell",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{level=\"INFO\", server=~\"$server\", botType=~\"bank.*\"}",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Connected Accounts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time({exporter=\"OTLP\", source=\"snowbot\", botType=~\"Controller.*\"} \r\n  | json count=\"body.connectedAccountsCount\" \r\n  | count >= 0 \r\n  | __error__=\"\"\r\n  | unwrap count [5m])"
    }
   ]
  },
  {
   "title": "Banned Accounts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time({exporter=\"OTLP\", source=\"snowbot\", botType=~\"Controller.*\"} \r\n  | json count=\"body.bannedAccountsCount\" \r\n  | count >= 0 \r\n  | __error__=\"\"\r\n  | unwrap count [5m])"
    }
   ]
  },
  {
   "title": "Trying to connect Accounts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time({exporter=\"OTLP\", source=\"snowbot\", botType=~\"Controller.*\"} \r\n  | json count=\"body.tryingtoConnectAccountsCount\" \r\n  | count >= 0 \r\n  | __error__=\"\"\r\n  | unwrap count [5m])"
    }
   ]
  },
  { "title": "Total Kamas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Total Value (m kamas)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(\r\n    last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} \r\n      | json bot_id=\"body.character.id\", kamas=\"body.kamas.bruts\" \r\n      | unwrap kamas | __error__=\"\" [2d])\r\n)\r\n+\r\nsum(\r\n    last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} \r\n      | json bot_id=\"body.character.id\", kamas=\"body.kamas.inBank\" \r\n      | kamas > 0 \r\n      | unwrap kamas | __error__=\"\" [2d])\r\n)\r\n+\r\nsum(\r\n    last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} \r\n      | json bot_id=\"body.character.id\", kamas=\"body.kamas.inHdv\" \r\n      | kamas > 0 \r\n      | unwrap kamas | __error__=\"\" [2d])\r\n)",
     "legendFormat": "Total Value (m kamas)"
    }
   ]
  },
  {
   "title": "Total Value évolution",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.bruts\"  | unwrap k | __error__=\"\" [2d]))\r\n  - \r\n  sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.bruts\" | unwrap k | __error__=\"\" [2d] offset $__range))\r\n)\r\n+\r\n(\r\n  sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inBank\" | k > 0 | unwrap k | __error__=\"\" [2d]))\r\n  - \r\n  sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inBank\" | k > 0  | unwrap k | __error__=\"\" [2d] offset $__range))\r\n)\r\n+\r\n(\r\n  sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inHdv\" | k > 0  | unwrap k | __error__=\"\" [2d]))\r\n  - \r\n  sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inHdv\" | k > 0  | unwrap k | __error__=\"\" [2d] offset $__range))\r\n)"
    }
   ]
  },
  {
   "title": "Evolution Per bot",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bot_id, server, botType) (\r\n  last_over_time(\r\n    {level=\"INFO\", server=~\"$server\", botType =~\"$botType\"} \r\n      | json bot_id=\"body.character.id\", botType=\"body.botType\", bruts=\"body.kamas.bruts\"\r\n      | unwrap bruts \r\n      | __error__=\"\"\r\n      [2d]\r\n  )\r\n)"
    },
    {
     "expr": "(\r\n  sum by (bot_id) (last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json bot_id=\"body.character.id\", k=\"body.kamas.bruts\" | unwrap k | __error__=\"\" [2d])) +\r\n  sum by (bot_id) (last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json bot_id=\"body.character.id\", k=\"body.kamas.inBank\" | k > 0 | unwrap k | __error__=\"\" [2d])) +\r\n  sum by (bot_id) (last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json bot_id=\"body.character.id\", k=\"body.kamas.inHdv\" | k > 0 | unwrap k | __error__=\"\" [2d]))\r\n)\r\n- \r\n(\r\n  sum by (bot_id) (last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json bot_id=\"body.character.id\", k=\"body.kamas.bruts\" | unwrap k | __error__=\"\" [2d] offset $__range)) +\r\n  sum by (bot_id) (last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json bot_id=\"body.character.id\", k=\"body.kamas.inBank\" | k > 0 | unwrap k | __error__=\"\" [2d] offset $__range)) +\r\n  sum by (bot_id) (last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json bot_id=\"body.character.id\", k=\"body.kamas.inHdv\" | k > 0 | unwrap k | __error__=\"\" [2d] offset $__range))\r\n)"
    }
   ]
  },
  {
   "title": "Total Value évolution %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  (\r\n    sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.bruts\" | unwrap k | __error__=\"\" [2d])) +\r\n    sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inBank\" | unwrap k | k > 0  | __error__=\"\" [2d])) +\r\n    sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inHdv\" | unwrap k  | k > 0 | __error__=\"\" [2d]))\r\n  )\r\n  - \r\n  (\r\n    sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.bruts\" | unwrap k | __error__=\"\" [2d] offset $__range)) +\r\n    sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inBank\" | unwrap k | k > 0  | __error__=\"\" [2d] offset $__range)) +\r\n    sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inHdv\" | unwrap k | k > 0  | __error__=\"\" [2d] offset $__range))\r\n  )\r\n)\r\n/\r\n(\r\n  sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.bruts\" | unwrap k | __error__=\"\" [2d] offset $__range)) +\r\n  sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inBank\" | unwrap k | k > 0  | __error__=\"\" [2d] offset $__range)) +\r\n  sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inHdv\" | unwrap k | k > 0  | __error__=\"\" [2d] offset $__range))\r\n)"
    }
   ]
  },
  { "title": "Kamas Bruts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Kamas bruts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(\r\n    last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} \r\n      | json bot_id=\"body.character.id\", kamas=\"body.kamas.bruts\" \r\n      | unwrap kamas | __error__=\"\" [2d])\r\n)",
     "legendFormat": "Kamas Bruts (m)"
    }
   ]
  },
  {
   "title": "Kamas bruts during period",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.bruts\" | unwrap k | __error__=\"\" [2d]))\r\n  - \r\n  sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.bruts\" | unwrap k | __error__=\"\" [2d] offset $__range))\r\n)"
    }
   ]
  },
  {
   "title": "Evolution Per bot",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bot_id, server, botType) (\r\n  last_over_time(\r\n    {level=\"INFO\", server=~\"$server\", botType =~\"$botType\"} \r\n      | json bot_id=\"body.character.id\", botType=\"body.botType\", bruts=\"body.kamas.bruts\"\r\n      | unwrap bruts \r\n      | __error__=\"\"\r\n      [2d]\r\n  )\r\n)"
    },
    {
     "expr": "sum by (bot_id) (\r\n  last_over_time({level=\"INFO\", server=~\"$server\", botType =~\"$botType\"} | json bot_id=\"body.character.id\", bruts=\"body.kamas.bruts\" | unwrap bruts | __error__=\"\" [2d] )\r\n)\r\n-\r\nsum by (bot_id) (\r\n  last_over_time({level=\"INFO\", server=~\"$server\", botType =~\"$botType\"} | json bot_id=\"body.character.id\", bruts=\"body.kamas.bruts\" | unwrap bruts | __error__=\"\" [2d] offset $__range)\r\n)"
    }
   ]
  },
  {
   "title": "Kamas bruts evolution %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  (\r\n    sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.bruts\" | unwrap k | __error__=\"\" [2d]))\r\n  )\r\n  - \r\n  (\r\n    sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.bruts\" | unwrap k | __error__=\"\" [2d] offset $__range))\r\n  )\r\n)\r\n/\r\n(\r\n  sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.bruts\" | unwrap k | __error__=\"\" [2d] offset $__range))\r\n)"
    }
   ]
  },
  { "title": "Bank Value", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Kamas in bank",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(\r\n    last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} \r\n      | json bot_id=\"body.character.id\", kamas=\"body.kamas.inBank\" \r\n      | kamas > 0 \r\n      | unwrap kamas | __error__=\"\" [2d])\r\n)",
     "legendFormat": "Bank estimation"
    }
   ]
  },
  {
   "title": "Bank Value évolution",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inBank\"  | k > 0 | unwrap k | __error__=\"\" [2d]))\r\n  - \r\n  sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inBank\"  | k > 0 | unwrap k | __error__=\"\" [2d] offset $__range))\r\n)"
    }
   ]
  },
  {
   "title": "Evolution Per bot",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bot_id, server, botType) (\r\n  last_over_time(\r\n    {level=\"INFO\", server=~\"$server\", botType =~\"$botType\"} \r\n      | json bot_id=\"body.character.id\", bruts=\"body.kamas.inBank\"\r\n      | unwrap bruts \r\n      | __error__=\"\"\r\n      [2d]\r\n  )\r\n)"
    },
    {
     "expr": "sum by (bot_id) (\r\n  last_over_time({level=\"INFO\", server=~\"$server\", botType =~\"$botType\"} | json bot_id=\"body.character.id\", bruts=\"body.kamas.inBank\" | unwrap bruts | __error__=\"\" [2d])\r\n)\r\n-\r\nsum by (bot_id) (\r\n  last_over_time({level=\"INFO\", server=~\"$server\", botType =~\"$botType\"} | json bot_id=\"body.character.id\", bruts=\"body.kamas.inBank\" | unwrap bruts | __error__=\"\" [2d] offset $__range)\r\n)"
    }
   ]
  },
  {
   "title": "Bank Value évolution %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  (\r\n    sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inBank\"  | k > 0 | unwrap k | __error__=\"\" [2d])) \r\n  )\r\n  - \r\n  (\r\n    sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inBank\" | k > 0  | unwrap k | __error__=\"\" [2d] offset $__range))\r\n  )\r\n)\r\n/\r\n(\r\n  sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inBank\"  | k > 0 | unwrap k | __error__=\"\" [2d] offset $__range))\r\n)"
    }
   ]
  },
  { "title": "HDV Value", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Kamas HDV",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(\r\n    last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} \r\n      | json bot_id=\"body.character.id\", kamas=\"body.kamas.inHdv\" \r\n      | kamas > 0 \r\n      | unwrap kamas | __error__=\"\" [2d])\r\n)",
     "legendFormat": "HDV estimation (m)"
    }
   ]
  },
  {
   "title": "HDV estimation during period",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inHdv\" | k > 0  | unwrap k | __error__=\"\" [2d]))\r\n  - \r\n  sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inHdv\"  | k > 0 | unwrap k | __error__=\"\" [2d] offset $__range))\r\n)"
    }
   ]
  },
  {
   "title": "Evolution Per bot",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (bot_id, server, botType) (\r\n  last_over_time(\r\n    {level=\"INFO\", server=~\"$server\", botType =~\"$botType\"} \r\n      | json bot_id=\"body.character.id\", botType=\"body.botType\", kamas=\"body.kamas.inHdv\"\r\n      | kamas > 0\r\n      | unwrap kamas \r\n      | __error__=\"\"\r\n      [2d]\r\n  )\r\n)"
    },
    {
     "expr": "sum by (bot_id) (\r\n  last_over_time({level=\"INFO\", server=~\"$server\", botType =~\"$botType\"} | json bot_id=\"body.character.id\", kamas=\"body.kamas.inHdv\" | kamas > 0 | unwrap kamas | __error__=\"\" [2d])\r\n)\r\n-\r\nsum by (bot_id) (\r\n  last_over_time({level=\"INFO\", server=~\"$server\", botType =~\"$botType\"} | json bot_id=\"body.character.id\", kamas=\"body.kamas.inHdv\" | kamas > 0 | unwrap kamas | __error__=\"\" [2d] offset $__range)\r\n)"
    }
   ]
  },
  {
   "title": "HDV estimation evolution %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  (\r\n    sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inHdv\" | k > 0 | unwrap k | __error__=\"\" [2d]))\r\n  )\r\n  - \r\n  (\r\n    sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inHdv\" | k > 0 | unwrap k | __error__=\"\" [2d] offset $__range))\r\n  )\r\n)\r\n/\r\n(\r\n  sum(last_over_time({level=\"INFO\", server=~\"$server\", botType=~\"$botType\"} | json k=\"body.kamas.inHdv\" | k > 0 | unwrap k | __error__=\"\" [2d] offset $__range))\r\n)"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Summary of Craft bots",
     "type": "table",
     "gridPos": { "h": 16, "w": 18, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (bot_id, server, botType) (\r\n  last_over_time(\r\n    {level=\"INFO\", server=~\"$server\", botType!~\".*bank.*\"} \r\n      | json bot_id=\"body.character.id\", botType=\"body.botType\", bruts=\"body.kamas.bruts\"\r\n      | unwrap bruts \r\n      | __error__=\"\"\r\n      [1d]\r\n  )\r\n)"
      },
      {
       "expr": "sum by (bot_id) (\r\n  last_over_time(\r\n    {level=\"INFO\", server=~\"$server\", botType!~\".*bank.*\"} \r\n      | json bot_id=\"body.character.id\", bank=\"body.kamas.inBank\"\r\n      | unwrap bank \r\n      | __error__=\"\"\r\n      [1d]\r\n  )\r\n)"
      },
      {
       "expr": "sum by (bot_id) (\r\n  last_over_time(\r\n    {level=\"INFO\", server=~\"$server\", botType!~\".*bank.*\"} \r\n      | json bot_id=\"body.character.id\", hdv=\"body.kamas.inHdv\"\r\n      | unwrap hdv \r\n      | __error__=\"\"\r\n      [1d]\r\n  )\r\n)"
      },
      {
       "expr": "(\r\n  sum by (bot_id) (last_over_time({level=\"INFO\", server=~\"$server\"} | json bot_id=\"body.character.id\", k=\"body.kamas.bruts\" | unwrap k | __error__=\"\" [1d])) +\r\n  sum by (bot_id) (last_over_time({level=\"INFO\", server=~\"$server\"} | json bot_id=\"body.character.id\", k=\"body.kamas.inBank\" | unwrap k | __error__=\"\" [1d])) +\r\n  sum by (bot_id) (last_over_time({level=\"INFO\", server=~\"$server\"} | json bot_id=\"body.character.id\", k=\"body.kamas.inHdv\" | unwrap k | __error__=\"\" [1d]))\r\n)\r\n- \r\n(\r\n  sum by (bot_id) (last_over_time({level=\"INFO\", server=~\"$server\"} | json bot_id=\"body.character.id\", k=\"body.kamas.bruts\" | unwrap k | __error__=\"\" [1d] offset $__range)) +\r\n  sum by (bot_id) (last_over_time({level=\"INFO\", server=~\"$server\"} | json bot_id=\"body.character.id\", k=\"body.kamas.inBank\" | unwrap k | __error__=\"\" [1d] offset $__range)) +\r\n  sum by (bot_id) (last_over_time({level=\"INFO\", server=~\"$server\"} | json bot_id=\"body.character.id\", k=\"body.kamas.inHdv\" | unwrap k | __error__=\"\" [1d] offset $__range))\r\n)"
      }
     ]
    }
   ]
  },
  { "title": "log ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Ingestion flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum(rate({exporter=\"OTLP\"} [$__interval]))",
     "legendFormat": "Total ingestion"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\", server=~\"$server\", botType=~\"$botType\"} | json"
    }
   ]
  }
 ]
}